<?php
$categories = $this->getStoreCategories(true, false, true);
$categoryHelper = $this->getCategoryHelper();
?>
<ul class="category-tree">
    <?php foreach ($categories as $category):
    if ($category->getName() == 'Men'){
      if (!$category->getIsActive()) {
        continue;
      } ?>
          <li class = "margin-bawah-footer-ktgr"> <a href="<?php echo $categoryHelper->getCategoryUrl(
            $category
          ); ?>"><?php echo $category->getName(); ?></a>
          </li>
        <?php if (
          $childrenCategories = $this->getChildCategories($category)
        ): ?>
              <ul class = "margin-bawah-footer-ktgr">
                  <?php foreach ($childrenCategories as $childrenCategory):
                    if (!$childrenCategory->getIsActive()) {
                      continue;
                    } ?>
                      <li class = "margin-bawah-footer-ktgr">
                          <a href="<?php echo $categoryHelper->getCategoryUrl(
                            $childrenCategory
                          ); ?>"><?php echo $childrenCategory->getName(); ?></a>
                      </li>
                      <?php
                  endforeach; ?>
              </ul>
            <?php endif;
    }
    endforeach; ?>
</ul>