<div class="text-container">
    <marquee class="running-text">これはニュースです | これはニュースです</marquee>
</div>

<div class="container-collection">
    <div class="item-collection colspan-2 title">
        <h2>新参者</h2>
        <h2>New Arrival</h2>
    </div>
    <div class="item-collection banner">
        <img class="img-collection" src='<?php echo $this->getViewFileUrl(
          'Moonlay_CustomHome::images/mcollection.jpg'
        ); ?>' />
        <div class="collection">
            <a href="#">メンズコレクション</a>
            <br />
            <a href="#">Men’s Collection</a>
        </div>
    </div>
    <div class="item-collection banner">
        <img class="img-collection" src='<?php echo $this->getViewFileUrl(
          'Moonlay_CustomHome::images/wcollection.jpg'
        ); ?>' />
        <div class="collection">
            <a href="#">女性のコレクション</a>
            <br />
            <a href="#">Women’s Collection</a>
        </div>
    </div>
</div>

<div class="container-about">
    <div class="item-about">
        <div class="about">
            <img class="about-logo" src='<?php echo $this->getViewFileUrl(
              'Moonlay_CustomHome::images/logo-white.png'
            ); ?>' />
            <p class="about-text">2013年に発売されたbateeqは、インドネシアのファッションブランドであり、新鮮で、 流行に敏感な男性、女性向けの衣料品ラインを通じてバティックを取り入れ、子供、家の装飾に加えて。革新的なモチーフで知られるbateeq 何世紀も昔の工芸品に現代的なエッジを提供して、楽なコレクションを作成します 今日の洗練されたデザインの既製のドレス、シャツ、ブラウス、パンツ 消費者および小売業者。</p>
            <button class="more">続きを読む</button>
        </div>
    </div>
    <div class="item-about video">
        <iframe src="https://www.youtube.com/embed/Y24R8hg_hvQ"></iframe>
    </div>
</div>

<div class="title">
    <h2>ランキング</h2>
    <h2>Ranking</h2>
</div>

<?php
$productsBlock = $this->getLayout()->createBlock(
  \Magento\CatalogWidget\Block\Product\ProductsList::class
);
$productsBlock->setTitle("My products");
$productsBlock->setProductsCount(5);
$productsBlock->setTemplate("product/widget/content/grid.phtml");
$productsBlock->setConditionsEncoded(
  "^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`28`^],`1--2`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`attribute_set_id`,`operator`:`==`,`value`:`4`^]^]"
);

echo $productsBlock->toHtml();


?>
