<div class="footer-socmed-container">
  <span>
    <img class="socmed-ig" src='<?php echo $this->getViewFileUrl(
      'Moonlay_CustomHome::images/instagram.png'
    ); ?>' alt="Instagram" />
  </span>
  <span>
    <img class="socmed-fb" src='<?php echo $this->getViewFileUrl(
      'Moonlay_CustomHome::images/facebook.png'
    ); ?>' alt="Facebook" />
  </span>
  <span>
    <img class="socmed-tw" src='<?php echo $this->getViewFileUrl(
      'Moonlay_CustomHome::images/twitter.png'
    ); ?>' alt="Twitter" />
  </span>
  <span>
    <a href="#">bateeqshop</a>
  </span>
</div>
