<div class="container-about m-5">
    <div class="item-about video">
        <iframe src="https://www.youtube.com/embed/<?= $block->escapeHtml(
          $block->getData('video_id')
        ) ?>" frameborder='0' allowfullscreen></iframe>
    </div>
    <div class="item-about">
        <div class="about" style="background-image: url(pub/media/<?= $block->escapeHtml(
          $block->getData('background_image')
        ) ?>), linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5));">
            <div class="about-text"><?= $block->getData('about') ?></div>
            <a href="/about-bateeq">
              <button class="more">ブランド「bateeq」について</button>
            </a>
        </div>
    </div>
</div>