<div class="container-about m-5">
    <div class="item-about video">
        <iframe src="https://www.youtube.com/embed/<?= $block->escapeHtml(
          $block->getData('video_id')
        ) ?>"></iframe>
    </div>
    <div class="item-about">
        <div class="about">
            <p class="about-text"><?= $block->escapeHtml(
              $block->getData('about')
            ) ?></p>
            <a href="/about-bateeq">
              <button class="more">ブランド「bateeq」について</button>
            </a>
        </div>
    </div>
</div>