<div class="container-collection">
    <div class="item-collection colspan-2 title">
        <h2><?= $block->escapeHtml($block->getData('title_jp')) ?></h2>
        <h2><?= $block->escapeHtml($block->getData('title_en')) ?></h2>
    </div>
    <div class="item-collection banner">
        <img class="img-collection" src='<?php echo $this->getViewFileUrl(
          'Moonlay_CustomHome::images/mcollection.jpg'
        ); ?>' />
        <div class="collection">
            <a href="<?= $block->escapeHtml(
              $block->getData('men_url')
            ) ?>"><?= $block->escapeHtml($block->getData('men_jp')) ?></a>
            <br />
            <a href="<?= $block->escapeHtml(
              $block->getData('men_url')
            ) ?>"><?= $block->escapeHtml($block->getData('men_en')) ?></a>
        </div>
    </div>
    <div class="item-collection banner">
        <img class="img-collection" src='<?php echo $this->getViewFileUrl(
          'Moonlay_CustomHome::images/wcollection.jpg'
        ); ?>' />
        <div class="collection">
            <a href="<?= $block->escapeHtml(
              $block->getData('women_url')
            ) ?>"><?= $block->escapeHtml($block->getData('women_jp')) ?></a>
            <br />
            <a href="<?= $block->escapeHtml(
              $block->getData('women_url')
            ) ?>"><?= $block->escapeHtml($block->getData('women_en')) ?></a>
        </div>
    </div>
</div>