<div class="footer-socmed-container">
  <span>
    <a href="<?= $block->escapeHtml($block->getData('ig_url')) ?>">
      <img class="socmed-ig" src='<?php echo $this->getViewFileUrl(
        'Moonlay_CustomHome::images/instagram.png'
      ); ?>' alt="Instagram" />
    </a>
  </span>
  <span>
    <a href="<?= $block->escapeHtml($block->getData('fb_url')) ?>">
      <img class="socmed-fb" src='<?php echo $this->getViewFileUrl(
        'Moonlay_CustomHome::images/facebook.png'
      ); ?>' alt="Facebook" />
    </a>
  </span>
  <span>
    <a href="<?= $block->escapeHtml($block->getData('tw_url')) ?>">
      <img class="socmed-tw" src='<?php echo $this->getViewFileUrl(
        'Moonlay_CustomHome::images/twitter.png'
      ); ?>' alt="Twitter" />
    </a>
  </span>
  <span>
    <?= $block->escapeHtml($block->getData('socmed_username')) ?>
  </span>
</div>
